<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Company>UniScan</Company>
        <AssemblyVersion>0.0.1</AssemblyVersion>
        <FileVersion>0.0.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\UniScan.Platform\UniScan.Platform.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    </ItemGroup>

</Project>
