<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0-android</TargetFramework>
        <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <ApplicationId>me.dexrn.uniscan.client.android</ApplicationId>
        <ApplicationVersion>1</ApplicationVersion>
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <AndroidPackageFormat>apk</AndroidPackageFormat>
        <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
        <Company>UniScan</Company>
        <Product>UniScan Android</Product>
        <AssemblyVersion>0.0.1</AssemblyVersion>
        <FileVersion>0.0.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <AndroidResource Include="Icon.png">
            <Link>Resources\drawable\Icon.png</Link>
        </AndroidResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Android"/>
        <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen"/>
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common.Jvm" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Android" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel.Android" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState.Android" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\UniScan.Platform.Implementations.Native\UniScan.Platform.Implementations.Native.csproj" />
        <ProjectReference Include="..\..\Core\UniScan.Platform\UniScan.Platform.csproj" />
        <ProjectReference Include="..\UniScan.Client.App\UniScan.Client.App.csproj" />
    </ItemGroup>
</Project>
