<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Company>UniScanProject</Company>
        <AssemblyVersion>0.3.0</AssemblyVersion>
        <FileVersion>0.3.0</FileVersion>
        <Description>Contains the protocol and shared networking code</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\external\Shiki\Extensions\Shiki.Extensions.MessagePack\Shiki.Extensions.MessagePack.csproj" />
        <ProjectReference Include="..\..\Core\UniScan.UserInterface\UniScan.UserInterface.csproj" />
        <ProjectReference Include="..\UniScan.Network.CodeGenerator\UniScan.Network.CodeGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\..\external\Shiki\Shiki.Common\Shiki.Common.csproj" />
      <ProjectReference Include="..\..\Core\UniScan.Core\UniScan.Core.csproj" />
      <ProjectReference Include="..\..\Core\UniScan.Device\UniScan.Device.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNetty.Buffers" Version="0.7.6" />
      <PackageReference Include="DotNetty.Codecs" Version="0.7.6" />
      <PackageReference Include="DotNetty.Common" Version="0.7.6" />
      <PackageReference Include="DotNetty.Handlers" Version="0.7.6" />
      <PackageReference Include="DotNetty.Transport" Version="0.7.6" />
      <PackageReference Include="MessagePack" Version="3.1.8" />
    </ItemGroup>

</Project>
