#nullable enable

using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Shiki.CodeGenerator.Core;

namespace UniScan.Network.CodeGenerator.Generator;

[Generator]
public class RequestConstructorAttributeImplGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
                              .CreateSyntaxProvider(
                                                    (node, _) =>
                                                        node is ClassDeclarationSyntax or RecordDeclarationSyntax
                                                         or StructDeclarationSyntax,
                                                    (ctx, _) =>
                                                    {
                                                        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not
                                                            INamedTypeSymbol c) return null;

                                                        List<Symbol> ctors =
                                                        [
                                                            .. from ctor in c.Constructors
                                                               let isFactoryConstructable = HasAttribute(ctor)
                                                               where isFactoryConstructable
                                                               select Symbol.FromMethodSymbol(ctor)
                                                        ];

                                                        return ctors;
                                                    }
                                                   );
        
        context.RegisterSourceOutput(provider, GenerateAll);
    }

    private bool HasAttribute(ISymbol symbol) => symbol.GetAttributes()
                                                       .Any(a =>
                                                                a.AttributeClass
                                                                ?.ToDisplayString() ==
                                                                "UniScan.Network.Request.RequestConstructorAttribute");

    private void GenerateAll(SourceProductionContext context, IEnumerable<Symbol>? symbols)
    {
        if (symbols == null)
            return;
        
        foreach (Symbol symbol in symbols)
        {
            Generate(context, symbol);
        }
    }

    private void Generate(SourceProductionContext context, Symbol symbol)
    {
        // while (!Debugger.IsAttached){}
        
        string usings = !symbol.Imports.IsEmpty ? "\n" : "";
        usings += string.Join("\n", symbol.Imports.Select(i => $"using {i};"));

        int idx = symbol.Params.IndexOf(("System.Guid?", "RequestId"));
        if (idx == -1)
        {
            return;
        }
        
        string? respType = null;
        foreach (var parent in symbol.Parents)
        {
            if (parent.TypeName == "IRequestPayloadPart")
            {
                respType = parent.TemplateParams[0];
                break;
            }
        }

        if (respType is null)
            return;
        
        var fp = symbol.Params.Where(p => p.TypeName != "Guid?" && p.Name != "RequestId").ToImmutableArray();
        string tp = string.Join(", ", fp.Select(p => p.TypeName).Prepend(string.Join(", ", symbol.FullClassName, respType)));

        List<string> v = [.. fp.Select(p => p.Name)];
        v.Insert(idx, "RequestManager.CreateRequestId()");
        
        string docs = "/// <inheritdoc/>";
        if (symbol.Documentation != null)
        {
            XElement member = XElement.Parse(symbol.Documentation);
            docs = "///" + string.Join("\n    ///", member.Nodes().SelectMany(n => n.ToString().Split([
                "\r\n", "\r", "\n"
            ], StringSplitOptions.None).Select(l => l.Trim())));
        }
        
        //is there not nicer way to do this
        //I wanted tree-like generation where I can define file with namespaces and usings and then class with fields and properties
        //and then turn it into file
        string source = $$"""
                          #nullable enable
                          
                          using UniScan.Network.Request;
                          using UniScan.Network.Request.Factory;{{usings}}
                          
                          namespace {{symbol.Namespace}};

                          /// <auto-generated />
                          public {{symbol.ClassKind}} {{symbol.FullClassName}} : IRequestFactoryConstructable<{{tp}}> {{(symbol.TemplateParams.Any(t => t.Constraint != null) ? "\n" + string.Join("\n", symbol.TemplateParams.Where(t => t.Constraint != null).Select(t => t.Constraint)) : "")}}
                          {
                              {{docs}}
                              public static {{symbol.FullClassName}} CreateRequest({{string.Join(", ", fp.Select(p => $"{p.TypeName} {p.Name}"))}}) => new({{string.Join(", ", v)}}); 
                          }

                          """;

        context.AddSource($"{ToFriendlyFilename(symbol.FullClassName)}.{ToFriendlyFilename(string.Join(".", fp.Select(p => p.TypeName)))}.g.cs",
                          SourceText.From(source, Encoding.UTF8));
    }

    private static string ToFriendlyFilename(string str) => Uri
                                                           .EscapeDataString(str
                                                                            .Replace("?", "_nullable")
                                                                            .Replace("<", "_tr_")
                                                                            .Replace(">", "_tl")
                                                                            .Replace(",", "_cm_")
                                                                            .Replace(" ", "")).Replace("%", "_");
}