<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0-ios</TargetFramework>
        <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <Description>UniScan client for iOS</Description>
        <AssemblyVersion>0.0.1</AssemblyVersion>
        <FileVersion>0.0.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.iOS"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\UniScan.Client.App\UniScan.Client.App.csproj" />
        <ProjectReference Include="..\UniScan.Client\UniScan.Client.csproj"/>
    </ItemGroup>
</Project>
