# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build UniScan Client (Web)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-client-web:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/publish" >> "$GITHUB_OUTPUT"

      - name: Build
        # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        run: >
          dotnet publish ${{github.workspace}}/Client/UniScan.Client.App.Platform.Web
          -c Release
          -o ${{steps.strings.outputs.build-output-dir}}        

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ${{steps.strings.outputs.build-output-dir}}/wwwroot
            
  publish-client-web:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-client-web
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4